openapi: 3.0.0
info:
  description: "This is Sample Customer Management API specification "
  version: 1.0.0
  title: Swagger Customer Management
  termsOfService: http://swagger.io/terms/
  contact:
    email: ultradev.nitc@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
tags:
  - name: Customer
    description: Customer Management
paths:
  /customers:
    post:
      tags:
        - Customer
      summary: Add a new customer
      description: ""
      operationId: createCustomer
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Customer"
        description: Customer Info Object
  
      responses:
        "201":
          description: "successfully created"
          content:
            application/json:
             schema:
              $ref: "#/components/schemas/CreateCustomerResponse"
        "405":
          description: Invalid input
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: http://localhost:8080/v2
components:
  schemas:
    Customer:
      type: object
      properties:

        customerId:
          type: integer
          format: int64
        name:
          type: string
        location:
          type: string
        email:
          type: string
          format: email
        address:
          type: string
          description: address
        status:
          type: boolean
          default: false
    CreateCustomerResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        customerId:
          type: integer
          format: int64
        name:
          type: string
        location:
          type: string
        email:
          type: string
          format: email
        address:
          type: string
          description: address
        status:
          type: boolean
          default: false
          
          
          